### PR TITLE
fix for 2013.09.02 AMIs

### PR DESCRIPTION
**Pull request by sebsto**
Hello Evan,

I fixed the issue with the new AMI (2013.09.02) page - when you will have time - can you review & pull these changes ?

Thanks

Seb

### CODE REVIEW

**Comment by evandbrown** [comment]
Nice work! Thanks, Seb.

**Comment by sebsto** [comment]
Hey, apparently you did not pull ... any reason ?  Looking for a more generic solution ?

**Comment by evandbrown** [comment]
Bah, I forgot to click 'Confirm merge' after I accepted...it's in now. Thanks!

**Comment by sebsto** [comment]
Thanks !
Don't you have anything to do on Christmas Eve ... :-) ??

Merry Christmas for you and your family.

--Seb

**Pull request merged**
